DATA:
  VIDEO_DIR_PATH: /datasets01/ego4d_track2/v1/full_scale
  ANN_DIR: ../data/fho/annotations/
  CLIPS_SAVE_PATH: ../data/fho/pos_clips
  NO_SC_PATH: ../data/fho/neg_clips
  SAMPLING_FPS: 2
  CLIP_LEN_SEC: 8
  CROP_SIZE: 225
  TASK: "keyframe_localization"
TRAIN:
  TRAIN_ENABLE: True
  DATASET: StateChangeDetectionAndKeyframeLocalisation
  BATCH_SIZE: 16
TEST:
  ENABLE: False
  BATCH_SIZE: 16
  DATASET: StateChangeDetectionAndKeyframeLocalisation
DATA_LOADER:
  NUM_WORKERS: 10
  PIN_MEMORY: True
  SHUFFLE: True
  IS_NO_STATE_CHANGE: False  # False - only load state change frames
MISC:
  FAST_DEV_RUN: False
  NUM_GPUS: 2
  OUTPUT_DIR: ./logs/pnr
  LOG_DIR: 'keyframe-bce-lrconstant'
MODEL:
  ARCH: "slow_layer5"
  NUM_CLASSES: [1]
  NUM_STATE_CLASSES: [2]
  HEAD_ACT: softmax
  MODEL_NAME: KeyframeLocalizationResNet
  LOSS_FUNC: "bce"
  LOSS_REDUCTION: "mean"
  KEYFRAME_DETECTION_ACT: "none"
SOLVER:
  BASE_LR: 0.0001
  MAX_EPOCH: 10
  OPTIMIZING_METHOD: "adamw"
  LR_POLICY: "constant"
