TRAIN:
  ENABLE: True
  DATASET: Ego4dRecognitionwithAuxTask
  BATCH_SIZE: 32
DATA:
  PATH_TO_DATA_DIR: "../data/lta/annotations"
  PATH_PREFIX: "../data/lta/clips"
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  TASK: "classification2loader"
  TARGET_FPS: 30
  CHECKPOINT_MODULE_FILE_PATH: ""
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 101
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [23, 23], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 1e-4
  LR_POLICY: cosine_warmup
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  OPTIMIZING_METHOD: sgd
  WEIGHT_DECAY: 1e-4
MODEL:
  NUM_CLASSES: [115, 478]
  ARCH: slowfast
  MODEL_NAME: TaskFusionMFTransformer3Task
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  FREEZE_BACKBONE: False
  TRANSLATION_LAYERS: 3
  TRANSLATION_INPUT_FEATURES: 128
  TRANSLATION_DROPOUT: 0.1
TEST:
  ENABLE: True
  DATASET: Ego4dRecognitionwithAuxTask
  BATCH_SIZE: 32
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: './logs/ar'
CHECKPOINT_LOAD_MODEL_HEAD: False
CHECKPOINT_FILE_PATH: ""
PRETRAIN:
  PNR_CFG: "./configs/eval/pnr.yaml"
  PNR_FT: True
  OSCC_CFG: "./configs/eval/oscc.yaml"
  OSCC_FT: True
  ACTION_CFG: "./configs/eval/recognition.yaml"
  ACTION_FT: True
